---
ip: '192.168.57.13'

ssh_key_users: [barman]
ssh_known_hosts_user: '{{ ssh_key_users }}'
ssh_known_hosts_list:
  - '{{ hostvars["leader"].ip }}'

barman_config_servers:
  leader:
    ssh_command: ssh postgres@{{ hostvars["leader"].ip }}
    conninfo: host={{ hostvars["leader"].ip}} user={{
      barman_user }} port=5432 dbname=postgres
    streaming_conninfo: host={{ hostvars["leader"].ip}} user={{ barman_user }}

pgpass_files:
  /var/lib/barman/.pgpass:
    owner: barman
    passwords:
      - server: '{{ hostvars["leader"].ip}}'
        user: '{{ barman_user }}'
        password: '{{ barman_password }}'
...
