---

postgresql_config_hba: []
postgresql_config_hba_default:
  - type: local
    database: all
    user: all
    address:
    method: peer
  - type: local
    database: replication
    user: all
    address:
    method: peer
postgresql_config_default:
  max_connections: 100
  shared_buffers: 128MB
  dynamic_shared_memory_type: posix
  max_wal_size: 1GB
  min_wal_size: 80MB
  logging_collector: true
  log_directory: log
  log_filename: postgresql-%a.log
  log_truncate_on_rotation: true
  log_rotation_age: 1d
  log_rotation_size: 0
  log_line_prefix: '%m [%p] '
  log_timezone: Europe/Moscow
  datestyle: iso, mdy
  timezone: Europe/Moscow
  lc_messages: en_US.UTF-8
  lc_monetary: en_US.UTF-8
  lc_numeric: en_US.UTF-8
  lc_time: en_US.UTF-8
  default_text_search_config: pg_catalog.english
postgresql_config_override: {}
...
